### ISSUE TITLE
Distribition setting

### ISSUE THREAD

**Issue by pcabfever** [sendbird/sendbird-uikit-ios#8]
Hey Sendbird

According to the docs we need to strip the simulator architecture to distribute an app that includes sendbird-uikit

https://docs.sendbird.com/ios/ui_kit_getting_started#3_distribution_setting

You don´t mention that in the readme of this project.

The question is, is it necessary? if so, we are getting an error when installing the app in a device regarding 

![image](https://user-images.githubusercontent.com/40566477/81668291-be52b600-9444-11ea-94a5-0e097d9c7bb9.png)

Can you clarify, please?

Thanks in advance

**Comment by tezpark** [comment]
Hello, @pcabfever 

Sorry for the confusion.
I added the relevant content to the README.

Since our framework is provided in the form of a fat binary, it is necessary to remove unnecessary arches when distributing an AppStore.
You do not need to do this unless you are in a deployment situation.

Thank you for reporting the issue.
